// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkrVikSIlKiA47xlCVIwZ3aU_hAxxAb94',
    appId: '1:747239573441:web:6be50fbb1103ed14301140',
    messagingSenderId: '747239573441',
    projectId: 'fir-firestore-curd',
    authDomain: 'fir-firestore-curd.firebaseapp.com',
    storageBucket: 'fir-firestore-curd.firebasestorage.app',
    measurementId: 'G-8CQM1KZ7LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDotZW1eswksZ6NyfbgQ4NRnOVRpRMRuXE',
    appId: '1:747239573441:android:0103bdbd1ae9fffa301140',
    messagingSenderId: '747239573441',
    projectId: 'fir-firestore-curd',
    storageBucket: 'fir-firestore-curd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoOtsOEC1TnCA7JB_tlyn6nXH3c9RvYsc',
    appId: '1:747239573441:ios:e5f9fbefa68024e2301140',
    messagingSenderId: '747239573441',
    projectId: 'fir-firestore-curd',
    storageBucket: 'fir-firestore-curd.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseCurd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkrVikSIlKiA47xlCVIwZ3aU_hAxxAb94',
    appId: '1:747239573441:web:00f3f3824129eb7e301140',
    messagingSenderId: '747239573441',
    projectId: 'fir-firestore-curd',
    authDomain: 'fir-firestore-curd.firebaseapp.com',
    storageBucket: 'fir-firestore-curd.firebasestorage.app',
    measurementId: 'G-T8FM2KH8NM',
  );
}
